paper/paper.md
Adds DOE grant number from Astronum paper (please check).
=> Add acknowledgements section.

paper/paper.md
simply -> simple and capitalize Jacobian
=> Fix paper typos

examples/urca-23_starkiller/actual_network.F90, examples/urca-23_starkiller/actual_rhs.F90, pynucastro/networks/base_fortran_network.py, pynucastro/networks/rate_collection.py, pynucastro/templates/starkiller-microphysics/actual_network.F90.template, pynucastro/templates/starkiller-microphysics/actual_rhs.F90.template
this updates to the new format in starkiller outlined here:
https://github.com/starkiller-astro/Microphysics/pull/220
=> New starkiller format

pynucastro/networks/base_fortran_network.py, pynucastro/templates/starkiller-microphysics/actual_network.F90.template
this sync us up to the StarKiller Microphysics PR https://github.com/starkiller-astro/Microphysics/pull/258
=> add aion_inv to the starkiller nets

examples/pp-CNO-example.ipynb, pynucastro/networks/rate_collection.py
we can now specify the ydot_cutoff_value to only show rates about a threshold.
We can also now force the plot to show p or alpha, even if they are not consumed,
using always_show_p=True or always_show_alpha=True
=> add some enhancements to the Explorer

pynucastro/networks/base_fortran_network.py, pynucastro/networks/rate_collection.py
since the other networks are derived from this, this allows them
to also more easily incorporate screening
=> move the screening factors function into the base RateCollection

pynucastro/networks/base_cxx_network.py, pynucastro/networks/base_fortran_network.py, pynucastro/networks/starkiller_cxx_network.py, pynucastro/networks/starkiller_network.py, pynucastro/networks/tests/_starkiller_reference/inputs.burn_cell.VODE, pynucastro/templates/starkiller-microphysics/inputs.burn_cell.VODE.template
also fix the format of the inputs file for burn_cell
=> remove some unused functions in base_cxx_network.py

pynucastro/networks/rate_collection.py
this gives more control over the attributes of the plot
=> More plot options

pynucastro/networks/rate_collection.py
this plots A - 2Z vs. Z, giving a more horizontal view of the network
=> add a new "rotated" plot type

examples/CNO/burn.py, examples/burn.py, pynucastro/nucdata/AtomicMassEvaluation/ame_nuclide.py, pynucastro/nucdata/AtomicMassEvaluation/ame_table.py, pynucastro/nucdata/binding_nuclide.py, pynucastro/nucdata/binding_table.py
=> remove future imports

pynucastro/rates/rate.py
this puts lighter nuclei reactions first and reactions with heavier
nuclei last
=> sort the library when we print

pynucastro/rates/rate.py
This change speeds up reading the 20180319default2 library by around 4x (from 20 seconds to 5 seconds on my machine).
=> Speed up reading library files

docs/source/intro.rst, pynucastro/networks/base_cxx_network.py, pynucastro/networks/base_fortran_network.py, pynucastro/rates/rate.py
This also now lists the member variables of Nucleus in the API docs
=> add the nuclear binding energy as a prop of Nucleus

requirements.txt
see https://github.com/sphinx-doc/sphinx/issues/10289
=> work around a bug in updated jinja + nbconvert

docs/source/index.rst, docs/source/modify-example.ipynb, docs/source/validate-example.ipynb
also clean up the validate example docs
=> add documentation on modifying rates

pynucastro/rates/tests/test_rates.py
=> add a unit test for tabular rates

docs/notes.txt, docs/source/pynucastro.nucleus.rst, docs/source/pynucastro.rst
Regenerate the API docs to include pynucastro.nucleus, and adjust the command so it doesn't include setup.py
=> Update API docs

pynucastro/rates/library.py
=> add a warning if a nucleus couldn't be linked

docs/source/index.rst
=> split the docs into sections

pynucastro/networks/rate_collection.py, pynucastro/networks/tests/test_rate_collection.py
this also refactors some exisiting code to use the new methods
=> add some more methods for finding reverse rates

pynucastro/networks/base_cxx_network.py, pynucastro/networks/python_network.py, pynucastro/networks/rate_collection.py, pynucastro/networks/tests/test_python_net2.py, setup.py
both the PythonNetwork and StarKillerCxxNetwork now correctly set
the ydot term to 0.0
this also reorganizes some code and adds a unit test
=> add support for inert nuclei in the network

pynucastro/networks/base_cxx_network.py, pynucastro/networks/python_network.py, pynucastro/networks/rate_collection.py, pynucastro/networks/sympy_network_support.py, pynucastro/nucdata/binding_nuclide.py, pynucastro/nucdata/elements.py, pynucastro/nucdata/mass_nuclide.py, pynucastro/nucdata/partition_function.py, pynucastro/nucdata/spin_nuclide.py, pynucastro/rates/rate.py, pyproject.toml
* fix a typo in ApproximateRate: `__set_screening()` -> `_set_screening()`
* remove else blocks after a return statement (no-else-return)
* iterate over .items() or .values() in dictionaries (consider-using-dict-items)
* replace `dict()` with `{}` (use-dict-literal)
* update old-style class definitions (useless-object-inheritance)
* replace .format() with f-strings (consider-using-f-string)
* do membership checks directly on a dictionary instead of through .keys() (consider-iterating-dictionary)
* use isinstance() for typechecks (unidiomatic-typecheck)
* simplify some boolean expressions (unnecessary-not)
* reduce nesting in RateCollection.plot() (too-many-nested-blocks)
=> Apply pylint suggestions

pynucastro/rates/rate.py
This PR adds `derived` on the derived rates. This is useful to differentiate both.
=> Label for derived rates

pynucastro/networks/base_cxx_network.py, pynucastro/networks/rate_collection.py, pynucastro/screening/screen.py
Addresses rate evaluation part of #287
=> Add screening to RateCollection

pynucastro/networks/rate_collection.py, pynucastro/networks/tests/test_rate_collection.py
=> Add a method to RateCollection that finds unimportant rates

pynucastro/networks/rate_collection.py
add the capability to turn on or off coulomb correction term for nse calculation.
=> switch coulomb

pynucastro/screening/__init__.py, pynucastro/screening/screen.py
I have included Potekhin (1998) screening routine compatible with Zhi's NSE chemical potential. Two things remain to be performed:
1. To implement Chugunov (2009) free energy in order to compute the NSE chemical potential and test differences.
2. To implement a perturbative scheme in the NSE routine to prevent overflowing. (A situation I am experimenting)
In this implementation, I plan to compute the dscor_dT and add it to this PR before it's merged.
=> Adding new screening routine

pynucastro/networks/rate_collection.py
let spin = 1.0 for nuclei that don't have spin state in the record.
=> add default spin values for nuclei for nse calculation

docs/source/index.rst
this support is now included in python networks
=> remove the warning that we don't support partition functions

pynucastro/rates/rate.py
allows the option to use `TabularRate.plot()` to plot the energy loss due to neutrinos for a range of denisty/temp
=> add ability to plot neutrino loss for tabular rates

pynucastro/networks/rate_collection.py
add different normalization to color bar, attempt to address issue #423
=> add additional normalization for color bar for different scales

pynucastro/networks/rate_collection.py
Addresses issue #409 . 
I'm wondering if we should make edges different from the approx rate edges.
=> Plot rates for rates < ydot_cutoff_value

CHANGES
This tags version 2.0.0 and updates the changes
=> pynucastro 2.0

pynucastro/rates/rate.py
Also store the tabular data as floats instead of strings.
=> Load tabular rates faster

README.md, pyproject.toml, setup.py
these fields seem to be the ones used by twine to upload to PyPI
=> fix URL in setup.py add descrition to pyproject.toml

CHANGES
I am going to mint 2.0.1 to test out recent changes for PyPI
=> update changes for 2.0.1

.mailmap
this ensures that `git shortlog -sn` properly groups contributions together
=> update the mailmap

pynucastro/rates/rate.py
ReacLibRate and TabularRate were nearly doing the same thing here
closes #469
=> move ydot_string_py and jacobian_string_py to the RateClass

pynucastro/networks/tests/test_approx_python_net.py
this also tests approximate rates and the chugunov 2007 screening
=> add an integration test for python networks

pynucastro/networks/rate_collection.py
remove_rates() can now act on a single Rate and a new method add_rates() will append Rate objects to the RateCollection.  In both cases, the RateCollection will be rebuilt
=> update RateCollection to make it easier to add / remove rates

pynucastro/rates/rate.py, pynucastro/rates/tests/test_rates.py
this mirrors how eval() is done.
Also add unit tests that compare to the finite-diff approx
=> add a method to evaluate the T derivative of ReacLibRate

code_of_conduct.md
this is based off the AstroPy code of conduct
=> add a code of conduct

docs/source/conf.py, docs/source/pynucastro.networks.rst, docs/source/pynucastro.nucdata.rst
=> add the "edit on github" link to docs

requirements.txt
=> Remove sphinx version requirement

docs/source/conf.py
See https://sphinx-rtd-theme.readthedocs.io/en/1.2.0/changelog.html#known-issues
=> Fix broken search in docs

pynucastro/networks/amrexastro_cxx_network.py, pynucastro/networks/base_cxx_network.py, pynucastro/networks/sympy_network_support.py, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_network.H, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_rhs.H, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/reaclib_rates.H, pynucastro/networks/tests/_amrexastro_cxx_reference/actual_network.H, pynucastro/networks/tests/_amrexastro_cxx_reference/actual_rhs.H, pynucastro/networks/tests/_amrexastro_cxx_reference/reaclib_rates.H, pynucastro/networks/tests/test_cxx_amrexastro_net.py, pynucastro/rates/rate.py
we should not use __ in C++ names
=> change the C++ rate names to be clang-tidy friendly

.github/workflows/isort.yml
Show what changes need to be made if imports aren't sorted correctly.
=> Improve isort error messages

.github/workflows/docs-test.yml, .gitignore, pynucastro/rates/rate.py
Also add docs/build to gitignore.
=> Turn Sphinx warnings into errors in the CI test

pynucastro/networks/tests/_amrexastro_cxx_approx_reference/table_rates.H, pynucastro/networks/tests/_amrexastro_cxx_reference/table_rates.H, pynucastro/templates/amrexastro-cxx-microphysics/table_rates.H.template
Now includes the correct variables and units from #297.
=> Update comment about the expected format in table_rates.H

docs/source/index.rst, docs/source/julia.rst
this makes the main index a bit clearer
=> move the Julia example docs to a subsection

pynucastro/networks/tests/conftest.py, pynucastro/networks/tests/helpers.py, pynucastro/networks/tests/test_cxx_amrexastro_approx_net.py, pynucastro/networks/tests/test_cxx_amrexastro_net.py
This will make it easier to add more C++ network tests.
=> Pull C++ write_network testing into a helper function

pynucastro/networks/rate_collection.py, pynucastro/networks/tests/test_rate_collection.py, pynucastro/rates/library.py
also fix the logic for these function (also in Library) to not add a rate if it already exists
=> add tests for RateCollection add_rates and remove_rates

pynucastro/networks/tests/_amrexastro_cxx_approx_reference/table_rates.H, pynucastro/networks/tests/_amrexastro_cxx_reference/table_rates.H, pynucastro/templates/amrexastro-cxx-microphysics/table_rates.H.template
Fixes AMReX-Astro/Microphysics#1261.
=> Rework init_tab_info() to avoid a VLA

pynucastro/networks/base_cxx_network.py, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/partition_functions.H, pynucastro/networks/tests/_amrexastro_cxx_reference/partition_functions.H, pynucastro/templates/amrexastro-cxx-microphysics/partition_functions.H.template
This lets the compiler know about the array sizes.
=> Template interpolate_pf() on npts

pynucastro/networks/base_cxx_network.py, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/reaclib_rates.H, pynucastro/networks/tests/_amrexastro_cxx_derived_reference/reaclib_rates.H, pynucastro/networks/tests/_amrexastro_cxx_reference/reaclib_rates.H, pynucastro/templates/amrexastro-cxx-microphysics/reaclib_rates.H.template
=> remove an amrex-specific statement from base_cxx_network

.github/workflows/cxx-network.yml
This adds more coverage for #553
=> Add ase network to C++ CI test

pynucastro/rates/tests/test_library_rates_by_name.py
we should test "he3(he3,pp)he4", since we recently fixed that
=> fix a comment in test_library_rates_by_name.py and add a test

pynucastro/rates/rate.py
this means classes that derive from this won't have issues if we test on it
=> define reverse=None in the base Rate class

pyproject.toml, requirements.txt, setup.py
=> Fix setuptools_scm error during build

examples/rp-process/network.ipynb, examples/rp-process/rp_process.py
Clean up flake8 warnings, simplify the code, and improve performance from ~40s to 25s by pre-filtering the reduced library.
=> Improve rp-process example script

docs/source/index.rst
NSE is moved to a new section that will be expanded soon Julia is moved to a retitled "Writing and Integrating Networks" section
=> a little doc reorganization

docs/source/pynucastro.networks.rst, pynucastro/networks/numpy_network.py, pynucastro/networks/tests/test_numpy_network.py, pynucastro/reduction/drgep.py, pynucastro/reduction/tests/test_drgep.py
Simplify the array caching and clean up the docs.
=> Clean up NumpyNetwork

pynucastro/networks/amrexastro_cxx_network.py, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_network.H, pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_network_data.cpp, pynucastro/networks/tests/_amrexastro_cxx_derived_reference/actual_network.H, pynucastro/networks/tests/_amrexastro_cxx_derived_reference/actual_network_data.cpp, pynucastro/networks/tests/_amrexastro_cxx_reference/actual_network.H, pynucastro/networks/tests/_amrexastro_cxx_reference/actual_network_data.cpp, pynucastro/networks/tests/test_cxx_amrexastro_net.py, pynucastro/templates/amrexastro-cxx-microphysics/actual_network.H.template, pynucastro/templates/amrexastro-cxx-microphysics/actual_network_data.cpp.template
This eliminates some managed memory on GPUs.
=> make bion/mion in AMReX-Astro nets constexpr

.github/workflows/cxx-network.yml, .github/workflows/docs-test.yml, .github/workflows/flake8.yml, .github/workflows/gh-pages.yml, .github/workflows/isort.yml, .github/workflows/pylint.yml, .github/workflows/pytest-all.yml, .github/workflows/simple-cxx-network.yml
=> update github action versions

pynucastro/networks/rate_collection.py, pynucastro/networks/tests/test_composition.py
Add `Composition.set_random()` method for generating random, normalized mass fraction distributions
=> Add Composition.set_random()

docs/source/refs.bib
this seems to work well with the linkcheck
=> remove sciencedirect links for DOIs are used instead

.github/workflows/cxx-network.yml, .github/workflows/microphysics-benchmarks/subch_simple_unit_test.out
=> replace subch_approx with subch_simple in unit test

docs/source/plot-types.ipynb, docs/source/screening-examples.ipynb, pynucastro/networks/rate_collection.py, pyproject.toml
adds warning if Reaclib n-decay rate is included when building a network. address #761
=> add warning about n-decay rate

pyproject.toml
pylint just dropped a new release and we fail
=> remove new pylint check on too-many-positional-arguments

docs/source/refs.bib, docs/source/sources.rst
=> update the physical constants docs

pynucastro/__init__.py, pynucastro/nucdata/__init__.py, pynucastro/nucdata/mass_table.py, pynucastro/nucdata/nucleus.py
this returns a list will all nuclei with known masses currently this is 3558 nuclei.
=> add a `get_all_nuclei()` method

pynucastro/networks/rate_collection.py, pynucastro/rates/approximate_rates.py
this makes it a lot clearer to read the approximations
=> store the approx child rates as a dict

pynucastro/networks/python_network.py, pynucastro/networks/tests/_python_reference/network.py, pynucastro/rates/rate.py
Counterpart to 4f4a38ad (#820).
=> Allow using rho and Y in PythonNetwork rates

pynucastro/numba_util.py, pynucastro/rates/rate.py, pynucastro/screening/screen.py
=> Pull out numba fallbacks into a separate submodule

docs/source/amrex-astro-cxx-networks.rst, docs/source/sources.rst
also add a warning that we do not check if we evaluate outside of the tabulation in C++
=> add doc about the limits of the weak rate tabulations

pynucastro/networks/rate_collection.py
this allows us to know the total number of rates in the network, since get_rates() does not account for those that are hidden
=> add a get_hidden_rates helper

pynucastro/networks/rate_collection.py, pynucastro/rates/__init__.py, pynucastro/rates/rate.py, pynucastro/rates/tests/test_rates.py, pyproject.toml
and hook this into the Rate class
=> add a BaryonConservationError exception

README.md
this should fix its display on PyPI
=> switch the logo in README to external link

docs/source/duplicate-rates.ipynb
=> fix a few issues on the dealing with duplicate rates doc page

pynucastro/networks/rate_collection.py
this can be used to help understand if a network can be used with explicit integrators
=> add a function to compute the spectral radius of the Jacobian

pynucastro/eos/fermi_integrals.py
This gets ~ 33% performance boost
=> use Numba on the Fermi kernel for performance

.github/workflows/cxx-network.yml
we changed it in a recent Microphysics PR
=> update name of ECSN network script in C++ CI action

pynucastro/library/tabular/pruet_fuller/parse_pruet.py
this will all be fixed for good once #1091 is merged.  This just suppresses the flake8 errors until then.
=> fix some flake8 stuff for the mistakenly committed pruet rates

.github/workflows/cxx-network.yml, .github/workflows/microphysics-benchmarks/subch_simple_unit_test.out
this is due to recent Microphysics changes
=> update C++ network CI

pynucastro/rates/library.py
this only makes sense for ReacLibRate objects
=> move Library.write_to_file to ReacLibLibrary

pynucastro/rates/library.py, pynucastro/rates/tests/test_ratefilter.py
this is a common need with the reduction algorithms
=> add an endpoint option to RateFilter

pynucastro/rates/tests/test_rates.py
it is now enabled and the tolerance was changed to get it to pass
=> the test on derived rate comparing our value with ReacLib was not enabled
