reaclib.py
test/replace-standard.py
test/standard/C_f90/network.f90
test/standard/URCA_f90/network.f90
test/standard/chapters/chapters_rhs.py
test/standard/triple-alpha/triple-alpha_rhs.py
test/standard/triple-alpha_f90/network.f90
test/test_reaclib.py

closes #5 
**Pure python unit testing**
test_reaclib.py now eliminates the use of subprocess.Popen. Instead, it:
- Imports test case scripts as modules
- Un-Imports each test case module when finished with it, along with any modules it may have imported
(The above is necessary to allow different test cases to use the same script name, eg. cno.py for both examples/CNO and examples/CNO_f90)
- Uses the difflib library to compare the outputs instead of using subprocess.Popen to call diff
**Explicit Prefactor Precision**
- Rate.prefactor is now printed in scientific notation in both python and fortran output.
- In fortran output, the exponent character is 'd' instead of 'e' to declare it as a double-precision value, as per Doug's suggestion.

Pure python unit testing and explicit precision

---

pyreaclib/networks/base_fortran_network.py
pyreaclib/networks/python_network.py

This is to ensure reactant strings are formed with nuclei in a consistent order.

Sort reactants after calling `set()`

---

examples/urca-23_starkiller/_parameters
examples/urca-23_starkiller/actual_network.F90
examples/urca-23_starkiller/actual_rhs.F90
examples/urca-23_starkiller/table_rates.F90
pynucastro/networks/base_fortran_network.py
pynucastro/templates/starkiller-microphysics/_parameters.template
pynucastro/templates/starkiller-microphysics/actual_network.F90.template
pynucastro/templates/starkiller-microphysics/actual_rhs.F90.template
pynucastro/templates/starkiller-microphysics/reaclib_rates.F90.template
pynucastro/templates/starkiller-microphysics/table_rates.F90.template

This PR fixes issues in the terms applied when using weak rates from the Suzuki, et al tabulation.
With these fixes, we agree with energy generation rates from MESA.

Apply tabular rate fixes from MESA comparison

---

pynucastro/rates/rate.py

This updates pynucastro's `list_known_rates()` function in the rates module to avoid attempting to read rates from `.py` or `.ipynb` files in the rate library directories.

In list_known_rates(), skip over python or jupyter notebook files.

---

pynucastro/rates/rate.py

When running some examples, I was getting a warning about this. numba.jitclass was moved to numba.experimental.jitclass. See [here](https://github.com/numba/numba/tree/master/numba/experimental).

jitclass -> experimental.jitclass

---

pynucastro/networks/starkiller_network.py

Chris Degrendele points out that we were writing NETWORK_PROPERTIES incorrectly for the latest version of StarKiller Microphysics.
We now do:
```
NSCREEN := [...]
NAUX := 0
```

Update NETWORK_PROPERTIES format for Starkiller Microphysics

---

pynucastro/networks/rate_collection.py

longer passes through to matplotlib, so zorder doesn't work anymore

networkx 2.5 requires linewidths instead of linewidth and no

---

README.md

I modified the README file, by stressing out that all the dependencies should be installed before pynucastro, otherwise, if this mistake occurs, installing pynucastro again should solve this issue.

Installation issue update in README

---

pynucastro/__init__.py
pynucastro/rates/__init__.py
pynucastro/rates/rate.py

A new ReacLibLibrary(Library) class is created to read the 20180319default2 library, without making an explicit mention of it.

Adding a default ReacLibLibrary(Library)

---

pynucastro/rates/rate.py

A new .forward() and .backward() selector functions are created with the purpose to separate the inverse ReacLib rates, computed by detailed balance.

Separating ReacLib reverse rates

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_starkiller_cxx_reference/actual_rhs.H

We update to use the new Microphysics interface that calculates the screening factors at compile time rather than runtime. This will allow us to ignore the cached screening factor array (because all of those factors are evaluated inline at compile time), which will ultimately simplify the networks.

Use constexpr screening interface

---

pynucastro/rates/library.py

this is > v2.2 from ReacLib, contains chapters 9, 10, 11, and
is in "version 2" format.  It was download on March 29, 2022

update to the latest ReacLib library

---

pynucastro/nucdata/binding_table.py

this greatly optimizes the get_nuclide() function, which is used
in the Rate constructor, so it improves the library read performance

switch binding_table to use a dict

---

pynucastro/rates/library.py
pynucastro/rates/rate.py

* Cache `Nucleus` objects when constructing `Rate`s to speed up loading
* Loop over the rates once in `linking_nuclei()` and use a set for faster membership checks
* Group rates in the full library by their reactants in `validate()`

Improve the performance of some Library operations

---

pynucastro/nucdata/spin_nuclide.py
pynucastro/nucdata/tests/test_spin.py

Adding the `test_spin.py` unit test and the `__eq__` dunder method to the `SpinNuclide` class

Adding unit test for SpinNuclide and SpinTable

---

docs/source/pynucastro.rst
docs/source/pynucastro.screening.rst
pynucastro/__init__.py
pynucastro/screening/__init__.py
pynucastro/screening/screen.py

This adds python screening routines based on [Chugunov, DeWitt, and Yakovlev 2007](https://journals.aps.org/prd/abstract/10.1103/PhysRevD.76.025028) and [Chugunov and DeWitt 2009](https://journals.aps.org/prc/abstract/10.1103/PhysRevC.80.014611).

Add python implementations of screening routines

---

pynucastro/rates/rate.py
setup.py

Make numba an optional dependency, under the "numba" extra. The generated python network code still needs numba.
Closes #292.

Allow the library code to run without numba

---

pynucastro/networks/tests/_starkiller_cxx_reference/table_rates.H
pynucastro/networks/tests/_starkiller_reference/table_rates.F90
pynucastro/templates/starkiller-cxx-microphysics/table_rates.H.template
pynucastro/templates/starkiller-microphysics/table_rates.F90.template

Fixes issue #154 . 
Appears there was a typo of mixing up `itemp_lo` for `itemp_hi` when checking if at top of the table. 
Also changed `itemp_lo+2` to `itemp_hi+1` as I think that is clearer than the previous format.

fix out of bounds issue

---

pynucastro/rates/rate.py

This adds a method to get the neutrino loss rate for tabulated rates. Is necessary to include neutrino losses when evaluating  energy generation as mentioned in #301

retrieve neutrino loss for tabulated rates

---

pynucastro/networks/rate_collection.py

Replaces original _symlog function with matplotlib class: `matplotlib.scale.SymmetricalLogTransform`, and function `transform_non_affine`.

replace mpl function for _symlog

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_starkiller_cxx_reference/actual_rhs.H
pynucastro/networks/tests/_starkiller_cxx_reference/reaclib_rates.H
pynucastro/templates/starkiller-cxx-microphysics/actual_rhs.H.template
pynucastro/templates/starkiller-cxx-microphysics/reaclib_rates.H.template

This screening hook is no longer needed since we've switched over to the compile-time screening evaluation.

Remove old screening hook

---

pynucastro/rates/rate.py

Use Python's native `sum()` instead of `np.sum()`, which has a lot of overhead for small lists.

Speed up rate construction

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_starkiller_cxx_reference/actual_network.H
pynucastro/templates/starkiller-cxx-microphysics/actual_network.H.template

note: because we use 1-based indexing, we pad the [0] of the vector
so we line up with the rate enum

add the string names of the rates to actual_network.H

---

pynucastro/networks/python_network.py
pynucastro/networks/rate_collection.py
pynucastro/nucdata/binding_table.py
pynucastro/nucdata/elements.py
pynucastro/nucdata/partition_function.py
pynucastro/nucleus/nucleus.py
pynucastro/rates/library.py
pynucastro/rates/rate.py

Replace `except AssertionError` with explicit checks, add error messages
to exceptions rather than printing them, and use more specific exception
classes where applicable.

Clean up error handling

---

.github/workflows/cxx-network.yml

we now generate and test subch_approx and ECSN
this extends coverage to approximate rates and tabular rates

update the burn_cell CI

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/python_network.py
pynucastro/networks/starkiller_cxx_network.py
pynucastro/nucdata/__init__.py
pynucastro/nucdata/binding_table.py
pynucastro/nucdata/mass_nuclide.py
pynucastro/nucdata/nucleus.py
pynucastro/nucdata/spin_nuclide.py
pynucastro/rates/library.py
pyproject.toml

This gets rid of the warnings about circular imports and avoids any
potential ImportErrors if the imports in `__init__.py` get reordered.

Use full paths for imports from sibling modules

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_starkiller_cxx_reference/table_rates.H
pynucastro/networks/tests/_starkiller_cxx_reference/table_rates_data.cpp
pynucastro/templates/starkiller-cxx-microphysics/table_rates.H.template

Having the filename of the tabulated data in the `table_t` struct causes problems when running with gpus (see Microphsyics [issue 952](https://github.com/AMReX-Astro/Microphysics/issues/952)).
Filename is only used at the initialization of the table, so can safely be removed from `table_t`

Move table filename out of meta data struct

---

pynucastro/networks/tests/conftest.py
pynucastro/networks/tests/test_approx_python_net.py
pynucastro/networks/tests/test_approx_screening.py
pynucastro/networks/tests/test_cxx_starkiller_net.py
pynucastro/networks/tests/test_networks.py
pynucastro/networks/tests/test_python_net.py
pynucastro/networks/tests/test_python_net2.py
pynucastro/networks/tests/test_rate_collection.py
pynucastro/networks/tests/test_screening.py
pynucastro/networks/tests/test_validate.py
pynucastro/nucdata/tests/test_binding.py
pynucastro/nucdata/tests/test_mass.py
pynucastro/nucdata/tests/test_partition.py
pynucastro/rates/tests/conftest.py
pynucastro/rates/tests/test_approx_rate.py
pynucastro/rates/tests/test_ratefilter.py
pynucastro/rates/tests/test_rates.py

This lets us load the ReacLib library once and automatically reuse it
for all of the tests, and some similar caching on a couple of other
expensive tests.
On my machine, this cuts the python tests (excluding the notebooks) from
3 minutes to 30 seconds.

Restructure tests to use pytest fixtures

---

pynucastro/rates/rate.py

Currently `TabularRate` isn't hashable. This breaks `RateCollection.evaulate_rates()` when a tabular rate is involved. The class doesn't inherit the `__hash__` from the `Rates` class because we changed the equality method.
This PR simply adds the `__hash__` explicitly in the `TabularRate` class.

make tabular rates hashable

---

pynucastro/__init__.py
pynucastro/networks/tests/test_python_partition_functions.py

this explicitly calls some rates with PF enabled to ensure that
we don't mess up their values

add a test of the partition function logic in python nets

---

pynucastro/networks/rate_collection.py
pynucastro/networks/tests/test_nse.py

1) Add unit test for nse. 
2) Filter out runtime warnings for fsolve, since we check convergence using np.isclose. 
3) Prevent overflow in exp by setting a cap number to the exponent.

Nse unit test

---

pynucastro/rates/rate.py

Currently the strings for tabular rates are messed up. For example.
```
>>> na23e_capture = TabularRate("na23--ne23-toki",)
>>> na23e_capture.string
'Na23 ⟶ Ne23 + e⁺ + 𝜈 + e⁺ + 𝜈'
```
There is double counting and clearly not an electron capture like it should be.
Cause to these two problems:
1. Double counting comes from `TabularRate._set_screening()` calling `_set_print_representation()` which leads to double counting electrons/neutrinos and other non-nuclei particles. 
2. Misidentifying this rate as a positron decay occurs because we don't set the `weak_type` for tabular rates. 
Fixes to these two problems
1. Remove the `_set_print_representation()` in screening. I don't think it is necessary there.
2. I set the `weak_type` by checking if the filename has "electroncapture" or …

Fix tabular strings

---

pynucastro/networks/rate_collection.py

`size` is actually in units of pixels

Fix RateCollection.plot() docstring

---

pynucastro/networks/rate_collection.py

The proton was missing from the u_c dictionary, consequently, networks without protons (like the approx13) had an undefined NSE state. This PR solves this issue.

Adding the proton nucleus into the u_c dictionary

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_rhs.H
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/table_rates.H
pynucastro/networks/tests/_amrexastro_cxx_reference/actual_rhs.H
pynucastro/networks/tests/_amrexastro_cxx_reference/table_rates.H
pynucastro/templates/amrexastro-cxx-microphysics/actual_rhs.H.template
pynucastro/templates/amrexastro-cxx-microphysics/table_rates.H.template

Under certain conditions, it is favorable for the product of a weak reaction to be in an excited state (e.g. electron captures at high density). In this case, a gamma ray is emitted providing some heating. The Suzuki et al. rates do account for this and there is a column labeled "gamma-heating". From what I've looked at, this heating is generally small compared to the neutrino loss.
this PR simply adds the heating into the amrex networks, similarly to how neutrino losses are implemented.

Add gamma heating to tabular weak rates

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/python_network.py
pynucastro/networks/rate_collection.py
pynucastro/nucdata/partition_function.py
pynucastro/nucdata/spin_table.py
pynucastro/rates/library.py
pynucastro/rates/rate.py

Notes on the non-trivial changes:
* `RateCollection.get_nuclei_needing_partition_functions()`: return an empty set instead of `None`
* `networks/python_network.py` & `networks/base_cxx_network.py`: the big diffs are just reduced nesting thanks to the previous change
* `nucdata/spin_table.py`: `self.datafile` will be opened in `_read_table()` which can raise a FileNotFoundError, so defer to that instead of raising our own exception

Fix lots of pylint suggestions

---

.github/workflows/pylint.yml
pynucastro/networks/rate_collection.py
pynucastro/rates/__init__.py
pynucastro/rates/library.py
pynucastro/rates/rate.py
pyproject.toml

Rate subclasses that deal with file input (currently ReacLibRate and TabularRate) should now only raise `RateFileError` or `UnsupportedNucleus`, instead of a mix of asserts and raw `Exception`.
This also turns on non-error checks in the pylint CI action, since it now runs cleanly.

Clean up Rate error handling

---

pynucastro/library/tabular/17o-17f_betadecay.dat
pynucastro/library/tabular/18o-18f_betadecay.dat
pynucastro/library/tabular/20f-20ne_betadecay.dat
pynucastro/library/tabular/20o-20f_betadecay.dat
pynucastro/library/tabular/21f-21ne_betadecay.dat
pynucastro/library/tabular/21o-21f_betadecay.dat
pynucastro/library/tabular/22f-22ne_betadecay.dat
pynucastro/library/tabular/23Ne-23Na_betadecay.dat
pynucastro/library/tabular/23f-23ne_betadecay.dat
pynucastro/library/tabular/24na-24mg_betadecay.dat
pynucastro/library/tabular/24ne-24na_betadecay.dat
pynucastro/library/tabular/25na-25mg_betadecay.dat
pynucastro/library/tabular/25ne-25na_betadecay.dat
pynucastro/library/tabular/26na-26mg_betadecay.dat
pynucastro/library/tabular/27mg-27al_betadecay.dat
pynucastro/library/tabular/27na-27mg_betadecay.dat
pynucastro/library/tabular/28al-28si_betadecay.dat
pynucastro/library/tabular/28mg-28al_betadecay.dat
pynucastro/library/tabular/28na-28mg_betadecay.dat

The beta-decay tables were not changed in #297 . This fixes that mistake

fix beta-decay table headers 

---

.coveragerc
.github/workflows/pytest-all.yml
examples/library-examples.ipynb
examples/rp-process/network.ipynb

Make pytest only count coverage on files in `pynucastro/`, add some standard exclusions to the coveragerc, and fix the metadata for some of the example notebooks so they work properly with nbval.

Improve pytest coverage reporting

---

pynucastro/networks/base_cxx_network.py
pynucastro/nucdata/elements.py

These were only used for the Fortran output and never got removed. Additionally, `PeriodicTable` doesn't need a no-op `__init__()`, since it should never be instantiated anyway.

Remove unused Fortran templates and unnecessary __init__()

---

pynucastro/rates/tests/test_rates.py

lower it for cases where we are comparing to small numbers

pytest.approx uses an default absolute tol of 1.e-12

---

pynucastro/rates/tests/test_tabular_rates.py

The tabular data used to generate the reference values only have 7 decimal digits of precision for the rates, and the original data from Suzuki et. al. only have 6 digits at most, so an rtol of 1e-9 is too strict.
Also print warnings if any rates are present in the library but not in the test file, rather than making the test fail.

Loosen tabular test tolerances and don't fail on new rates

---

pynucastro/networks/tests/test_cxx_amrexastro_approx_net.py
pynucastro/networks/tests/test_cxx_amrexastro_net.py
pyproject.toml

* Make isort work properly from any directory
* Make pylint stop complaining about mpi4py if it's installed
* Remove any existing files before writing a C++ network in the unit tests

Fix some development annoyances

---

pynucastro/networks/tests/test_approx_python_net.py
pynucastro/networks/tests/test_cxx_amrexastro_approx_net.py
pynucastro/networks/tests/test_cxx_amrexastro_net.py
pynucastro/networks/tests/test_full_python_net.py
pynucastro/networks/tests/test_python_partition_functions.py

Leave the files from failing tests alone, so the user can inspect them.

Remove generated files if a test passes

---

pynucastro/networks/tests/_amrexastro_cxx_approx_reference/table_rates.H
pynucastro/networks/tests/_amrexastro_cxx_reference/table_rates.H
pynucastro/templates/amrexastro-cxx-microphysics/table_rates.H.template

at high temperature, we were going out of bounds when computing the derivative

fix a bounds issue in the C++ table interpolation

---

requirements.txt

numpy 2.0 will be released in Dec/Jan, and they are recommending packages to put a < 2 version in their requirements until things are tested

set requirement for numpy<2

---

pynucastro/networks/rate_collection.py

This attribute was only used by `linking_nuclei()`, and it would go out of sync if any rates were added or removed. This PR removes it entirely, and instead builds a Library from the current list of rates as needed in `linking_nuclei()`.

Remove RateCollection.library

---

pynucastro/networks/rate_collection.py
pynucastro/nucdata/partition_function.py
pynucastro/nucdata/tests/test_nucleus.py
pynucastro/rates/rate.py

* Rewrite docstrings to use reST formatting and follow PEP-257
* Ensure `temperature` and `partition_function` are sorted numpy arrays
* Remove unnecessary handling for `interpolant_order = 0`
* Use `PartitionFunction.eval(T)` instead of `PartitionFunction(T)` for similarity with `Rate`
* Lazily construct the interpolant function, which reduces the import time by ~30%

Partition function improvements

---

pynucastro/networks/amrexastro_cxx_network.py
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_network.H
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_network_data.cpp
pynucastro/networks/tests/_amrexastro_cxx_reference/actual_network.H
pynucastro/networks/tests/_amrexastro_cxx_reference/actual_network_data.cpp
pynucastro/templates/amrexastro-cxx-microphysics/actual_network.H.template

with new pr 1279 in microphysics, this is no longer needed.

remove NSE_INDEX::initialized

---

.github/workflows/pytest-all.yml
conftest.py

This disables the AVX-512 routines when running pytest (both in CI and locally), which I needed in order to reproduce the same results as Github Actions on my machine.
It needs to go into the root of the repository because the environment variable has to be set before numpy is first imported. If we put it in `pynucastro/conftest.py`, pytest would import `pynucastro/__init__.py` first.

Move numpy AVX-512 workaround to conftest.py

---

pynucastro/networks/python_network.py

Fixed typo. When writing custom rates the temperature should be given as tf.

Change T to tf when writing custom rates

---

pynucastro/networks/rate_collection.py
pynucastro/rates/library.py

for example, in the p-p chain, we have
"he3(he3,pp)he4"
we will now correctly get the rate.  I also think we weren't handling the "aa" case correctly before.

fix get_rate_by_name to work with a rate with "pp"

---

pynucastro/networks/rate_collection.py
pynucastro/networks/tests/test_validate.py

this was only used for testing, and we can use pytest's capsys instead.
Also switch to keyword-only args

remove ostream from validate

---

pynucastro/networks/rate_collection.py

The alpha value here being a string was causing issues in matplotlib.colors (must be a relatively new change there I assume).
Should fix docs building is #624 and #635

fix issue in building docs

---

pynucastro/networks/rate_collection.py
pynucastro/networks/tests/test_composition.py

this is useful, for example, to preserve the amount if Ni56 when we bin down a composition

add an exclude option to bin_as

---

.github/workflows/pytest-all.yml
pyproject.toml

This lets us run pytest locally without having to pass all the `--ignore` options.

Move pytest exclusions to pyproject.toml

---

.github/workflows/microphysics-benchmarks/ecsn_unit_test.out
pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/actual_rhs.H
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/reaclib_rates.H
pynucastro/networks/tests/_amrexastro_cxx_derived_reference/actual_rhs.H
pynucastro/networks/tests/_amrexastro_cxx_derived_reference/reaclib_rates.H
pynucastro/networks/tests/_amrexastro_cxx_reference/actual_rhs.H
pynucastro/networks/tests/_amrexastro_cxx_reference/reaclib_rates.H
pynucastro/networks/tests/_simple_cxx_reference/reaclib_rates.H
pynucastro/templates/amrexastro-cxx-microphysics/actual_rhs.H.template

now we just accumulate it together in a single term instead of storing each rate's contribution separately in an Array1D

simplify how we account for weak rate neutrino loss

---

pynucastro/rates/library.py

we were bailing out of the search early.  Now we print a message and continue on to the next rate in the list.  This way we still return a list of rates even if one of the names doesn't exist.

for Library.get_rate_by_name we return None if any names don't exist

---

requirements.txt

Group packages by what they're needed for, and sort each group alphabetically.
This also replaces the `jupyter` requirement with `ipykernel`, as building the docs doesn't need the entire jupyter infrastructure.

Reorganize requirements.txt

---

pynucastro/networks/rate_collection.py

we are returning dY/dt but a user might expect r = n_A n_B <sigma v>

make the docs on evaluate_rates() clearer

---

pynucastro/networks/nse_network.py
pynucastro/networks/tests/test_nse.py

* replace more magic numbers with values from `scipy.constants`
* use `np.ndarray.copy()` instead of `copy.deepcopy()`
* scope the warning filter for `fsolve()`

More clean-up of the NSE solver

---

.github/workflows/microphysics-benchmarks/ase_nse_net_unit_test.out
.github/workflows/microphysics-benchmarks/ecsn_unit_test.out
.github/workflows/microphysics-benchmarks/subch_approx_unit_test.out

See AMReX-Astro/Microphysics#1380.
The subch_approx benchmark now matches the version before #677, but the ECSN one has changed (which matches what we saw with the benchmarks in Microphysics).

Update Microphysics benchmarks after sneut5 sin/cos fix

---

.github/workflows/cxx-network.yml
.github/workflows/docs-test.yml
.github/workflows/flake8.yml
.github/workflows/isort.yml
.github/workflows/pylint.yml
.github/workflows/pytest-all.yml
.github/workflows/simple-cxx-network.yml

Add the `workflow_dispatch` event to the test workflows, so we can run tests on a specific branch without needing to make a PR.

Allow manually triggering Github Actions tests

---

pynucastro/rates/known_duplicates.py

This speeds up the sensitivity analysis example code by ~10-15%.

Simplify and speed up duplicate rate checking

---

docs/source/Example-Integrating-Network-diffeqpy.ipynb
docs/source/Installing-Diffeqpy-Julia.ipynb
docs/source/NSE-example.ipynb
docs/source/conf.py
docs/source/electron-capture-example.ipynb
docs/source/electron-captures.ipynb
docs/source/index.rst
docs/source/intro.rst
docs/source/neutrino-cooling.ipynb
docs/source/partition-function.rst
docs/source/refs.bib
docs/source/screening-examples.ipynb
docs/source/sources.rst
docs/source/zreferences.rst
pynucastro/reduction/drgep.py
pynucastro/screening/screen.py
requirements.txt

Also fix some minor formatting issues.
See https://nbsphinx.readthedocs.io/en/latest/markdown-cells.html#Citations for the syntax for the in-notebook citations.
As a side note, the inner text of the <cite> tags gets entirely replaced with a formatted citation when building the docs. I left the original text in place, as it gets rendered weirdly in the Jupyter interface without it.

Add bibtex citations for all references

---

.github/workflows/pytest-all.yml

This makes it a lot easier to spot failing tests, and adds syntax highlighting to the tracebacks.

Enable color output in the pytest workflow

---

pynucastro/networks/tests/_amrexastro_cxx_approx_reference/partition_functions.H
pynucastro/networks/tests/_amrexastro_cxx_derived_reference/partition_functions.H
pynucastro/networks/tests/_amrexastro_cxx_reference/partition_functions.H
pynucastro/templates/amrexastro-cxx-microphysics/partition_functions.H.template

this mutes a clang-tidy warning

don't lint the missing default branch for spin switch

---

pynucastro/networks/base_cxx_network.py
pynucastro/networks/tests/_amrexastro_cxx_approx_reference/partition_functions.H
pynucastro/networks/tests/_amrexastro_cxx_derived_reference/partition_functions.H
pynucastro/networks/tests/_amrexastro_cxx_derived_reference/reaclib_rates.H
pynucastro/networks/tests/_amrexastro_cxx_reference/partition_functions.H
pynucastro/rates/rate.py
pynucastro/templates/amrexastro-cxx-microphysics/partition_functions.H.template

The partition function interpolation for derived rates is performed multiple times for most of the nuclei within `fill_reaclib_rates()`. This stores the interpolation results in a cache in that function so they can be reused by other rates, which gives a 10-15% overall speedup in my tests with subch_base.

Cache partition function interpolation in C++

---

.github/workflows/pylint.yml
pynucastro/networks/rate_collection.py
pynucastro/neutrino_cooling/sneut5.py

Also use the new GitHub output formatting, so we can see the annotations in context in the "Files changed" tab (for example, [`bd42732` (#733)](https://github.com/pynucastro/pynucastro/pull/733/commits/bd427326b66c26f1c77961a688e31c8a14742cd0)).

Address new pylint 3.2.0 warnings

---

pynucastro/networks/rate_collection.py

Restore the suppressions for `SymLogNorm` and remove the suppression for `mpl.colormaps.get_cmap()`, which were broken by astroid 3.2.0, and fixed in astroid 3.2.1.

Revert part of #733

---

.github/workflows/pytest-all.yml

This makes it much easier to compare package versions between runs to see if an update is causing any failures, rather than having to trawl through the install logs.

Print all installed packages in the pytest CI

---

requirements.txt

This was originally updated for Python 3.12, but pip should be able to get compatible versions on its own.

Relax numba version constraints

---

docs/source/conf.py

this adds more retries and a longer timeout
also allows for unauthorized responses (they are not failures)

make the linkcheck build more robust

---

docs/source/nucleus.ipynb
pynucastro/nucdata/partition_function.py

Fixes test failure with numpy < 2.0.

Cast the result of PartitionFunction.eval to a float

---

requirements.txt

this added a new warning that causes CI troubles

pin matplotlib < 3.10.0 temporarily

---

pynucastro/networks/rate_collection.py
requirements.txt

we are requiring that the axes use "datalim", so this is redundant. This removes a warning introduced in matplotlib 3.10.0

don't set the RateCollection.plot() limits explicitly

---

docs/source/NSE-example.ipynb
docs/source/electron-capture-example.ipynb
docs/source/electron-captures.ipynb
docs/source/neutrino-cooling.ipynb
docs/source/screening-examples.ipynb

This is much cleaner now, and uses the same roles as the ReST files. It's documented here, for reference: https://mystmd.org/guide/citations#citation-roles

Fix citations in notebooks after switching to myst-nb

---

CONTRIBUTING.md
docs/source/conf.py

now if we build with "SKIP_EXECUTE make html", sphinx will not
force-execute the Jupyter notebooks

allow executing of notebooks to be skipped

---

requirements.txt

I got an error when running locally with networkx 3.2.1 about the `connectionstyle` argument to `nx.draw_networkx_edge_labels()`, which is only available since networkx 3.3.
Also fix jupyterlab-myst so it works with conda-forge.

Update required networkx version

---

pynucastro/networks/rate_collection.py

they are only ever used once, and passed into the read routine

RateCollection doesn't need files as class data

---

.github/workflows/cxx-network.yml

we need to update the CI action to use the new name

fix NSE C++ test after Microphysics rename

---

pyproject.toml

this seems needed with the latest version of isort

have isort skip auto-generated _version.py

---

pyproject.toml

This PR adds settings for ruff that match our current selection of flake8 and pylint checks. ruff's checks overlap with many of the simpler pylint checks, but there are still quite a few useful ones in pylint that aren't implemented in ruff, so I don't think we want to switch over yet.

Add ruff settings for developer use

---

pynucastro/networks/tests/_fortran_reference/screen.H
pynucastro/networks/tests/_simple_cxx_reference/screen.H
pynucastro/templates/simple-cxx-network/screen.H.template

this is C++23 and not yet widely supported

in SimpleCxxNetwork screen.H, don't use std::pow in constexpr

---

pynucastro/networks/base_cxx_network.py

I think this was used to include neutrino loss from tabular rate to the energy generation rate. https://github.com/pynucastro/pynucastro/pull/152

remove unused enuc_add_energy_rate

---

setup.cfg
setup.py

these are no longer needed
the previous issue with the homepage in `pip show` needed the `setup.cfg` is no longer an issue.

remove setup.py and setup.cfg

---

LICENSE
pyproject.toml

the current method is deprecated
this also bumps up setuptools to a version that supports the new method, and updates the LICENSE copyright year.

update pyproject.toml license info
